from .goat import Goat
from .bearded_dragon import Bearded_dragon
from .buffalo import Buffalo
from .camel import Camel
from .catfish import Catfish
from .cobra import Cobra
from .crocodile import Crocodile
from .donkey import Donkey
from .gecko import Gecko
from .king_snake import King_snake
from .iguana import Iguana
from .llama import Llama
from .turtle import Turtle
from .falcon import Falcon
from .mallard import Mallard