from .Goat import Goat
from .Bearded_dragon import Bearded_dragon
from .Buffalo import Buffalo
from .Camel import Camel
from .Catfish import Catfish
from .Cobra import Cobra
from .Crocodile import Crocodile
from .Donkey import Donkey
from .Gecko import Gecko
from .King_snake import King_snake
from .Iguana import Iguana
from .Komodo_dragon import Komodo_dragon
from .Llama import Llama
from .Mallard import Mallard
from .Turtle import Turtle